Jest
FACN8/fizzbuzz pull request #1
Opened 2020-01-07 13:43 UTC by jamiecoe

I've updated the project to use `jest` instead of `tape` and `tap-spec`.

I've also updated the documentation and examples.

2020-01-07 22:35 UTC, Karyum approved these changes

2020-01-09 13:53 UTC, shiryz requested changes
One little thing

2020-01-09 13:53 UTC, shiryz commented on README.md
>  git clone https://github.com/foundersandcoders/fizzbuzz.git && cd fizzbuzz
Link is still to the fac one

2020-01-09 14:00 UTC, jamiecoe commented on README.md
>  git clone https://github.com/foundersandcoders/fizzbuzz.git && cd fizzbuzz
All sorted now 👍

2020-01-09 14:09 UTC, shiryz approved these changes

2020-01-09 14:09 UTC, merged